services:
  tailtunnel:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tailtunnel
    restart: unless-stopped
    environment:
      - TS_AUTHKEY=${TS_AUTHKEY}
      - STATE_DIR=/var/lib/tailtunnel
    volumes:
      - tailtunnel-state:/var/lib/tailtunnel

volumes:
  tailtunnel-state:
    driver: local
